{% macro PCCT_551506() -%}
 {################# Step 1 DECLARE SCRIPTS/DDL NEED TO EXECUTED #################}
{%- set v_scripts -%}

ALTER TABLE EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_SALES.PRODUCT RENAME TO EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_SALES.PRODUCT_ARCHIVE;
ALTER TABLE EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_ENGINEERING.PART RENAME TO EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_ENGINEERING.PART_ARCHIVE;


ALTER TABLE EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_SALES.PRODUCT_SCD1 RENAME TO EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_SALES.PRODUCT;
ALTER TABLE EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_ENGINEERING.PART_SCD1 RENAME TO EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_ENGINEERING.PART;


ALTER TABLE EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_SALES.PRODUCT_SCD2 RENAME TO EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_SALES.PRODUCT_HIST;
ALTER TABLE EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_ENGINEERING.PART_SCD2 RENAME TO EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_ENGINEERING.PART_HIST;



UPDATE EDL{{env_var('DBT_DEP_ENV')}}.UTILITY.EDW_PROCESS_INFO SET PROCESS_NAME='DBT_MART_SALES_PRODUCT_ARCHIVE' WHERE PROCESS_NAME='DBT_MART_SALES_PRODUCT';
UPDATE EDL{{env_var('DBT_DEP_ENV')}}.UTILITY.EDW_PROCESS_INFO SET PROCESS_NAME='DBT_MART_ENGINEERING_PART_ARCHIVE' WHERE PROCESS_NAME='DBT_MART_ENGINEERING_PART';


UPDATE EDL{{env_var('DBT_DEP_ENV')}}.UTILITY.EDW_PROCESS_INFO SET PROCESS_NAME='DBT_MART_SALES_PRODUCT' WHERE PROCESS_NAME='DBT_MART_SALES_PRODUCT_SCD1';
UPDATE EDL{{env_var('DBT_DEP_ENV')}}.UTILITY.EDW_PROCESS_INFO SET PROCESS_NAME='DBT_MART_ENGINEERING_PART' WHERE PROCESS_NAME='DBT_MART_ENGINEERING_PART_SCD1';


INSERT INTO EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_SALES.PRODUCT
(
PRODUCT_KEY,PRODUCT_ID,BIW_INS_DTTM,BIW_UPD_DTTM,BIW_BATCH_ID
)
SELECT MD5('-1'), '-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT (MIN(BATCH_ID)-1) 
    FROM EDL{{env_var('DBT_DEP_ENV')}}.UTILITY.EDW_PROCESS_BATCH_CTL CTL  
    JOIN EDL{{env_var('DBT_DEP_ENV')}}.UTILITY.EDW_PROCESS_INFO INFO 	
    ON CTL.PROCESS_ID = INFO.PROCESS_ID             
    AND INFO.PROCESS_NAME ='DBT_MART_SALES_PRODUCT'          
    AND CTL.BATCH_STATUS='S');

INSERT INTO EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_ENGINEERING.PART
(
PART_KEY,PART_ID, BIW_INS_DTTM,BIW_UPD_DTTM,BIW_BATCH_ID
)
SELECT MD5('-1'), '-1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT (MIN(BATCH_ID)-1) 
    FROM EDL{{env_var('DBT_DEP_ENV')}}.UTILITY.EDW_PROCESS_BATCH_CTL CTL  
    JOIN EDL{{env_var('DBT_DEP_ENV')}}.UTILITY.EDW_PROCESS_INFO INFO 	
    ON CTL.PROCESS_ID = INFO.PROCESS_ID             
    AND INFO.PROCESS_NAME ='DBT_MART_SALES_SALES_TERRITORY'          
    AND CTL.BATCH_STATUS='S');

DROP TABLE EDWNEW{{env_var('DBT_DEP_ENV')}}.MART_ENGINEERING.PART_HIST;

 {%endset%}

 {################# Step 2 EXECUTE SCRIPTS #################}
{% do run_query(v_scripts) %}

{################# Step 3 CAPTURE INTO DBT TABLE #################}
Insert into var('V_EDL_DEFAULT_DB')+env_var('DBT_DEP_ENV').UTILITY_DBT.DBT_SNOWFLAKE_DDL_EXECUTION
SELECT 
    551506 AS PCCT_NUMBER  ,
    '{{v_scripts|replace("'","''")}}' AS DDL_EXECUTED ,
    'RAMYA.NAGARAJ' AS BIW_CREATED_BY,
    CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ AS BIW_CREATED_DTTM,
    'RAMYA.NAGARAJ' AS BIW_UPD_BY ,
    CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ AS BIW_UPD_DTTM
{% endmacro %}